---
mail_server:  IP_OR_FQDN
helpdesk_account: test@example.com
helpdesk_password: FILL_ME_IN
ssl: 1
uid: 1
port: 993
mail_inbox_folder: Inbox
mail_processed_folder: 'Inbox/Addressed'
ticket_db: FILL_ME_IN
db_username: FILL_ME_IN
db_user_password: FILL_ME_IN
ticket_table: ticket
ignore_size_errors: 1