--- !!perl/hash:ReadConfig
'': ~
'%W, %M %m, %Y': ~
/usr/local/www/helpdesk/maps: ~
/usr/local/www/helpdesk/templates: ~
ARRAY(0x83da898): ~
ARRAY(0x83da964): ~
ARRAY(0x83db598): ~
ARRAY(0x85df6d4): ~
ARRAY(0x85df6ec): ~
ARRAY(0x85df704): ~
ARRAY(0x85df74c): ~
ARRAY(0x85df764): ~
ARRAY(0x85df77c): ~
ARRAY(0x85dfc34): ~
ARRAY(0x85dfc40): ~
ARRAY(0x85dfc58): ~
HASH(0x85df38c): ~
HASH(0x85df3f8): ~
HASH(0x85df9a0): ~
Pg: ~
Test company: ~
YAML: ~
auth: ~
auth_table: auth
ccboehd: ~
company_domain: test.com
company_name: Test company
comparisons: generic.cmps
config.yml: ~
config_dir: /usr/local/www/helpdesk/maps
config_file: config.yml
config_type: YAML
customer_backend: database
database: ~
date_format: '%W, %M %m, %Y'
db_name: ccboehd
db_password: helpdesk
db_type: Pg
db_user: helpdesk
default_app: helpdesk
generic.cmps: ~
helpdesk: ~
images/logo.jpg: ~
index.pl: ~
index_page: index.pl
localhost: ~
logo_image: images/logo.jpg
mail_server: localhost
newticket: ~
password: ~
pnd:
  equipment:
    form.pl:
      create:
        error_template: equipment/create.html
        form: equipment/create.form
        requirements: equipment/create.req
        template: equipment/submitted.html
      edit:
        form: equipment/edit.form
        template: equipment/edit.html
      new:
        form: equipment/create.form
        requirements: equipment/create.req
        template: equipment/create.html
      update:
        form: equipment/edit.form
        template: equipment/edit.html
    report.pl:
      custom:
        rmap: equipment/report.rmap
        template: equipment/report-view.html
      report:
        rmap: equipment/report.rmap
        template: equipment/report-view.html
      welcome:
        rmap: equipment/report-welcome.yaml
        template: equipment/report-welcome.html
  grants:
    form.pl:
      create:
        error_template: grants/create.html
        form: grants/create.form
        requirements: grants/create.req
        template: grants/submitted.html
      edit:
        form: grants/edit.form
        template: grants/edit.html
      new:
        form: grants/create.form
        requirements: grants/create.req
        template: grants/create.html
      update:
        form: grants/edit.form
        template: grants/edit.html
    report.pl:
      custom:
        rmap: grants/report.rmap
        template: grants/report-view.html
      report:
        rmap: grants/report.rmap
        template: grants/report-view.html
      welcome:
        rmap: grants/report-welcome.yaml
        template: grants/report-welcome.html
  hardware:
    form.pl:
      create:
        error_template: hardware/create.html
        form: hardware/create.form
        requirements: hardware/create.req
        template: hardware/submitted.html
      edit:
        form: hardware/edit.form
        template: hardware/edit.html
      new:
        form: hardware/create.form
        requirements: hardware/create.req
        template: hardware/create.html
      update:
        form: hardware/edit.form
        template: hardware/edit.html
    report.pl:
      custom:
        rmap: hardware/report.rmap
        template: hardware/report-view.html
      report:
        rmap: hardware/report.rmap
        template: hardware/report-view.html
      welcome:
        rmap: hardware/report-welcome.yaml
        template: hardware/report-welcome.html
  helpdesk:
    form.pl:
      create:
        error_template: ticket-new-create.html
        form: ticket-new.form
        requirements: ticket-new-create.req
        template: ticket-new-submitted.html
      edit:
        form: ticket-edit.form
        template: ticket-edit-view.html
      new:
        form: ticket-new.form
        template: ticket-new-create.html
      update:
        error_template: ticket-edit-view.html
        form: ticket-edit.form
        smap: ticket-edit-update.yml
        template: ticket-edit-view.html
      view:
        form: ticket-view-view.form
        template: ticket-view-view.html
    report.pl:
      custom:
        rmap: helpdesk-report.rmap
        template: report-view.html
      report:
        rmap: helpdesk-report.rmap
        template: report-view.html
      welcome:
        form: ticket-report-welcome.form
        template: report-welcome.html
  inventory:
    form.pl:
      create:
        error_template: inventory/new-create.html
        form: inventory/create.form
        requirements: inventory/new-create.req
        template: inventory/new-submitted.html
      edit:
        form: inventory/edit.form
        template: inventory/edit.html
      new:
        form: inventory/new.form
        requirements: inventory/new-create.req
        template: inventory/new-create.html
      update:
        form: inventory/edit.form
        template: inventory/edit.html
    report.pl:
      custom:
        rmap: inventory/report.rmap
        template: inventory/report-view.html
      report:
        rmap: inventory/report.rmap
        template: inventory/report-view.html
      welcome:
        form: inventory/report-welcome.yaml
        template: inventory/report-welcome.html
  purchases:
    form.pl:
      create:
        error_template: purchases/create.html
        form: purchases/create.form
        requirements: purchases/create.req
        template: purchases/submitted.html
      edit:
        form: purchases/edit.form
        template: purchases/edit.html
      new:
        form: purchases/create.form
        requirements: purchases/create.req
        template: purchases/create.html
      update:
        form: purchases/edit.form
        template: purchases/edit.html
    report.pl:
      custom:
        rmap: purchases/report.rmap
        template: purchases/report-view.html
      report:
        rmap: purchases/report.rmap
        template: purchases/report-view.html
      welcome:
        rmap: purchases/report-welcome.yaml
        template: purchases/report-welcome.html
  schools:
    report.pl:
      custom:
        rmap: school/report.rmap
        template: school/report-view.html
      report:
        rmap: school/report.rmap
        template: school/report-view.html
      welcome:
        rmap: school/report-welcome.yaml
        template: school/report-welcome.html
  software:
    form.pl:
      create:
        error_template: software/create.html
        form: software/create.form
        requirements: software/create.req
        template: software/submitted.html
      edit:
        form: software/edit.form
        template: software/edit.html
      new:
        form: software/create.form
        requirements: software/create.req
        template: software/create.html
      update:
        form: software/edit.form
        template: software/edit.html
    report.pl:
      custom:
        rmap: software/report.rmap
        template: software/report-view.html
      report:
        rmap: software/report.rmap
        template: software/report-view.html
      welcome:
        rmap: software/report-welcome.yaml
        template: software/report-welcome.html
  vendor:
    form.pl:
      create:
        error_template: vendor/create.html
        form: vendor/create.form
        requirements: vendor/create.req
        template: vendor/submitted.html
      edit:
        form: vendor/edit.form
        template: vendor/edit.html
      new:
        form: vendor/create.form
        requirements: vendor/create.req
        template: vendor/create.html
      update:
        form: vendor/edit.form
        template: vendor/edit.html
    report.pl:
      custom:
        rmap: vendor/report.rmap
        template: vendor/report-view.html
      report:
        rmap: vendor/report.rmap
        template: vendor/report-view.html
      welcome:
        rmap: vendor/report-welcome.yaml
        template: vendor/report-welcome.html
priority:
  - Low
  - Normal
  - High
  - Business Critical
sections:
  - Helpdesk
  - CM
  - App Dev
sites:
  - Test Site
  - Test
  - Test2
  - Test B
techs:
  - admin
  - test_user
  - test_user
template_dir: /usr/local/www/helpdesk/templates
test.com: ~
ticket_mail_account: newticket
ticket_mail_password: password
users: ~
users_table: users
