---
auth_table: auth
backend: database
backup_dir: %%BACKUP_DIR%%
backup_mask: 3
base_dn: %%BASE_DN%%
company_domain: %%COMPANY_DOMAIN%%
company_name: %%COMPANY_NAME%%
config_file: /usr/local/etc/opencop/config.yml
config_type: YAML
db_name: %%DB_NAME%%
db_password: %%DB_USER_PASSWORD%%
db_type: %%DB_TYPE%%
db_user: %%DB_USER%%
display_author: 1
display_barcode: 1
display_free_date: 1
display_free_time: 1
display_location: 1
display_serial: 1
directory_type: %%DIRECTORY_TYPE%%
directory_login_attribute: %%DIRECTORY_LOGIN_ATTRIBUTE%%
index_page: index.pl
ldap_port: 389
ldap_server: %%LDAP_SERVER%%
ldap_service_account: %%LDAP_SERVICE_ACCOUNT%%
ldap_service_password: %%LDAP_SERVICE_PASSWORD%%
logo_image: images/logo.png
mail_server: %%MAIL_SERVER%%
maximum_upload_file_size: %%UPLOAD_SIZE%%
support_email: %%SUPPORT_EMAIL_ADDRESS%%
support_phone_number: %%SUPPORT_PHONE_NUMBER%%
ticket_mail_account: %%TICKET_MAIL_ACCOUNT%%
ticket_mail_password: %%TICKET_MAIL_PASSWORD%%
update_url: update.agnqtech.com
upload_file_dir: %%UPLOAD_DIR%%
users_table: users
version: 1.0
