---
auth_table: auth
company_domain: test.com
company_name: Test company
config_file: config.yml
config_type: YAML
date_format: '%W, %M %m, %Y'
db_name: ccboehd
db_password: helpdesk
db_type: Pg
db_user: helpdesk
index_page: index.pl
logo_image: images/logo.jpg
mail_server: localhost
priority:
  - Low
  - Normal
  - High
  - Business Critical
sections:
  - Helpdesk
sites:
  - Test Site
techs:
  - admin
template_dir: /usr/local/www/helpdesk/templates
ticket_mail_account: newticket
ticket_mail_password: password
users_table: users
