---
auth_table: auth
company_domain: test.com
company_name: Test company
config_file: config.yml
config_type: YAML
date_format: '%W, %M %m, %Y'
db_name: ccboehd
db_password: helpdesk
db_type: Pg
db_user: helpdesk
index_page: index.pl
logo_image: images/logo.jpg
mail_server: localhost
priority:
  - Low
  - Normal
  - High
  - Business Critical
sections:
  - Helpdesk
sites:
  - Test Site
techs:
  - admin
template_dir: /usr/local/www/helpdesk/templates
ticket_mail_account: newticket
ticket_mail_password: password
users_table: users
version: .5
support_email: support@company.com
support_phone_number: 000-000-0000
#toggle switches for fields to display in the customer ticketing portal. 0 = off, 1 = on
display_barcode: 1
display_serial: 1
display_location: 1
display_author: 1
