template_dir: '/var/www/html/helpdesk-test/templates'
config_dir: '/var/www/html/helpdesk-test/maps'
db_user: collin
db_password: helpdesk
db_name: ccboehd
date_format: '%W, %M %m, %Y'
default_app: helpdesk
comparisons: generic.cmps

#pnd:
# app:
#  script.pl:
#   template: templatefile.html
#   form: ticked-edit-style_YML_mapfile.yml
#   rmap: report-style_YML_mapfile.yml
#   requirements: reqmap-style_YML_mapfile.yml
