---
auth_table: auth
company_domain: test.com
company_name: Test company
config_file: config.yml
config_type: YAML
date_format: '%W, %M %m, %Y'
db_name: ccboehd
db_password: helpdesk
db_type: Pg
db_user: helpdesk
display_author: 1
display_barcode: 1
display_free_date: 1
display_free_time: 1
display_location: 1
display_serial: 1
index_page: index.pl
logo_image: images/logo.jpg
mail_server: localhost
priority:
  - Low
  - Normal
  - High
  - Business Critical
sections:
  - Helpdesk
sites:
  - Test Site
  - test2
  - test2
  - test1
support_email: support@company.com
support_phone_number: 000-000-0000
techs:
  - admin
  - user2
template_dir: /usr/local/www/helpdesk/templates
ticket_mail_account: newticket
ticket_mail_password: password
users_table: users
version: .5
